name: sret_app
description: "Faculty Scheduling & Substitutions App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.3
  flutter_svg: ^2.0.9
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/brand/

# Flutter Native Splash configuration
flutter_native_splash:
  color: "#FFF7E6"
  # image: assets/brand/sret_logo.png  # Uncomment when you have PNG
  android_12:
    color: "#FFF7E6"
    # image: assets/brand/sret_logo.png  # Uncomment when you have PNG
